version: "3.9"

services:
  app:
    build: .
    container_name: template_name_sample
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
      - queue
      - cache
    depends_on:
      - database
      - queue
      - cache

  database:
    image: postgres
    container_name: database_name_sample
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=usernamesample
      - POSTGRES_PASSWORD=passwordsample
      - POSTGRES_DB=dbnamesample
    volumes:
      - database:/data/postgres

  queue:
    image: mongo:5.0
    container_name: queue_name_sample
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=usernamesample
      - MONGO_INITDB_ROOT_PASSWORD=passwordsample
    volumes:
      - queue:/data/mongo

  cache:
    image: redis:alpine
    container_name: cache_name_sample
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data/redis

volumes:
  database:
    driver: local
  queue:
    driver: local
  cache:
    driver: local
