version: "3.9"

services:
  app:
    build: .
    container_name: template_name_sample
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres
    container_name: database_name_sample
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=usernamesample
      - POSTGRES_PASSWORD=passwordsample
      - POSTGRES_DB=dbnamesample
