import { verify } from "jsonwebtoken";
import request from "supertest";

import { ForgotPasswordError } from "@modules/users/services/forgotPassword/ForgotPasswordError";
import { ResetPasswordError } from "@modules/users/services/resetPassword/ResetPasswordError";

import auth from "@config/auth";

import { BCryptHashProvider } from "@shared/containers/providers/HashProvider/implementations/BCryptHashProvider";
import { EtherealMailProvider } from "@shared/containers/providers/MailProvider/implementations/EtherealMailProvider";
import { app } from "@shared/infra/http/app";
import { pgDataSource } from "@shared/infra/typeorm/data-source";

import * as utilDate from "@utils/date";
import { compareInHours } from "@utils/date";

import { User } from "../../typeorm/entities/User";
import { EType, UserTokens } from "../../typeorm/entities/UserTokens";

let testUser: User;
let testToken: UserTokens;

describe("Forgot Password Controller", () => {
  beforeAll(async () => {
    // Connects at database and run migrations. It must be done in each test
    // controller file.
    await pgDataSource.initialize();
    await pgDataSource.runMigrations();

    // Create a user at "/api/v1/user" route to let possible to test sessions
    // controllers.
    const { body } = await request(app).post("/api/v1/user").send({
      name: "Name Sample",
      email: "sample@email.com",
      password: "samplepass",
    });

    // Put that new user information inside a var.
    testUser = {
      ...body,
      password: "samplepass",
    };
  });

  afterAll(async () => {
    // Delete and destroy entirely data.
    await pgDataSource.dropDatabase();
    await pgDataSource.destroy();
  });

  it("should be able to request a forgot password to the user", async () => {
    // Mock mail provider.
    const sendMail = jest
      .spyOn(EtherealMailProvider.prototype, "sendMail")
      // eslint-disable-next-line @typescript-eslint/no-empty-function
      .mockImplementationOnce(async () => {});

    // Request recovery password mail.
    const response = await request(app).post("/api/v1/password/forgot").send({
      email: testUser.email,
    });

    // Get the refresh token saved at database for expecting test analisys.
    const userToken = (await pgDataSource
      .createQueryBuilder<UserTokens>(UserTokens, "users_tokens")
      .where("users_tokens.user_id = :id", { id: testUser.id })
      .getOne()) as UserTokens;

    const { forgotSecret, forgotExpiresIn } = auth.jwt;
    const { type, createdAt, expiresAt, refreshToken } = userToken;

    expect(response.status).toBe(204);
    expect(sendMail).toHaveBeenCalled();
    expect(type).toBe(EType.forgotPassword);
    expect(verify(refreshToken, forgotSecret));
    expect(compareInHours(createdAt, expiresAt)).toBe(forgotExpiresIn);
  });

  it("should not be able to request a forgot password with an unfound email", async () => {
    const response = await request(app).post("/api/v1/password/forgot").send({
      email: "invalid@email.com",
    });

    // Get code and message error expected.
    const { statusCode, message } = new ForgotPasswordError.UserNotFound();

    expect(response.status).toBe(statusCode);
    expect(response.body.message).toBe(message);
  });
});

describe("Reset Password Controller", () => {
  beforeAll(async () => {
    // Connects at database and run migrations. It must be done in each test
    // controller file.
    await pgDataSource.initialize();
    await pgDataSource.runMigrations();

    // Create a user at "/api/v1/user" route to let possible to test sessions
    // controllers.
    const { body } = await request(app).post("/api/v1/user").send({
      name: "Name Sample",
      email: "sample@email.com",
      password: "samplepass",
    });

    // Put that new user information inside a var.
    testUser = {
      ...body,
      password: "samplepass",
    };
  });

  afterAll(async () => {
    // Delete and destroy entirely data.
    await pgDataSource.dropDatabase();
    await pgDataSource.destroy();
  });

  beforeEach(async () => {
    // Deleting all tokens to avoid JWT with same code.
    await pgDataSource.createQueryBuilder().delete().from(UserTokens).execute();

    // Mock mail provider.
    jest
      .spyOn(EtherealMailProvider.prototype, "sendMail")
      // eslint-disable-next-line @typescript-eslint/no-empty-function
      .mockImplementationOnce(async () => {});

    // Request recovery password mail at "/api/v1/password/forgot" route to
    // create a forgot token.
    await request(app).post("/api/v1/password/forgot").send({
      email: testUser.email,
    });

    // Getting forgot token generated by last recovery password requested.
    testToken = (await pgDataSource
      .createQueryBuilder<UserTokens>(UserTokens, "users_tokens")
      .where("users_tokens.user_id = :id", { id: testUser.id })
      .getOne()) as UserTokens;
  });

  it("should be able to reset user password", async () => {
    const newPass = "new-valid-password";

    // Mock hash provider.
    const generateHash = jest
      .spyOn(BCryptHashProvider.prototype, "generateHash")
      .mockImplementationOnce(async () => {
        return newPass;
      });

    // Request reset password for user.
    const response = await request(app).post("/api/v1/password/reset").send({
      token: testToken.refreshToken,
      password: newPass,
    });

    // Get the user saved at database for expecting test analisys.
    testUser = (await pgDataSource
      .createQueryBuilder<User>(User, "users")
      .where("users.id = :id", { id: testUser.id })
      .getOne()) as User;

    // Get the forgot token saved at database for expecting test analisys.
    testToken = (await pgDataSource
      .createQueryBuilder<UserTokens>(UserTokens, "users_tokens")
      .where("users_tokens.id = :id", { id: testToken.id })
      .getOne()) as UserTokens;

    const { password } = testUser;
    const { forgotSecret, forgotExpiresIn } = auth.jwt;
    const { type, createdAt, expiresAt, refreshToken } = testToken;

    expect(response.status).toBe(204);
    expect(generateHash).toHaveBeenCalled();
    expect(password).toBe(newPass);
    expect(type).toBe(EType.forgotPassword);
    expect(verify(refreshToken, forgotSecret));
    expect(testToken.getIsRevoked()).toBe(true);
    expect(compareInHours(createdAt, expiresAt)).toBe(forgotExpiresIn);
  });

  it("should not be able to reset password with an invalid token", async () => {
    const response = await request(app).post("/api/v1/password/reset").send({
      token: "invalid-refresh-token",
      password: "new-valid-password",
    });

    // Get code and message error expected.
    const { statusCode, message } = new ResetPasswordError.ForgotTokenInvalid();

    expect(response.body.message).toBe(message);
    expect(response.status).toBe(statusCode);
  });

  it("should not be able to reset password with an unfound token", async () => {
    // Deleting valid token in database.
    await pgDataSource
      .createQueryBuilder()
      .delete()
      .from(UserTokens)
      .where("refresh_token = :token", { token: testToken.refreshToken })
      .execute();

    const response = await request(app).post("/api/v1/password/reset").send({
      token: testToken.refreshToken,
      password: "new-valid-password",
    });

    // Get code and message error expected.
    const { statusCode, message } =
      new ResetPasswordError.ForgotTokenNotFound();

    expect(response.body.message).toBe(message);
    expect(response.status).toBe(statusCode);
  });

  it("should not be able to reset password with an expired token", async () => {
    jest.spyOn(utilDate, "dateNow").mockImplementation(() => {
      return new Date("2199-12-17T00:00:00");
    });

    const response = await request(app).post("/api/v1/password/reset").send({
      token: testToken.refreshToken,
      password: "new-valid-password",
    });

    // Get code and message error expected.
    const { statusCode, message } = new ResetPasswordError.ForgotTokenExpired();

    expect(response.body.message).toBe(message);
    expect(response.status).toBe(statusCode);
  });

  it("should not be able to reset password with an revoked token", async () => {
    await request(app).post("/api/v1/password/reset").send({
      token: testToken.refreshToken,
      password: "new-valid-password",
    });

    const response = await request(app).post("/api/v1/password/reset").send({
      token: testToken.refreshToken,
      password: "new-valid-password",
    });

    // Get code and message error expected.
    const { statusCode, message } = new ResetPasswordError.ForgotTokenRevoked();

    expect(response.body.message).toBe(message);
    expect(response.status).toBe(statusCode);
  });

  it("should not be able to reset password with an unfound user", async () => {
    // Deleting user in database.
    await pgDataSource.query(
      `UPDATE users SET email = 'invalid-mail' WHERE id = '${testUser.id}'`
    );

    const response = await request(app).post("/api/v1/password/reset").send({
      token: testToken.refreshToken,
      password: "new-valid-password",
    });

    // Get code and message error expected.
    const { statusCode, message } = new ResetPasswordError.UserNotFound();

    expect(response.body.message).toBe(message);
    expect(response.status).toBe(statusCode);
  });
});
