import request from "supertest";

import { app } from "@shared/infra/http/app";
import { pgDataSource } from "@shared/infra/typeorm/data-source";

import * as utilDate from "@utils/date";
import { delay } from "@utils/utils";

import { UserTokens } from "../../typeorm/entities/UserTokens";

let authUser: Record<string, unknown>;

describe("Authenticate Session Controller", () => {
  beforeAll(async () => {
    // Connects at database and run migrations. It must be done in each test
    // controller file.
    await pgDataSource.initialize();
    await pgDataSource.runMigrations();

    // Create a user at "/api/v1/user" route to let possible to test sessions
    // controllers.
    const { body } = await request(app).post("/api/v1/user").send({
      name: "Name Sample",
      email: "sample@email.com",
      password: "samplepass",
    });

    // Put that new user information inside a var.
    authUser = {
      ...body,
      password: "samplepass",
    };
  });

  afterAll(async () => {
    // Delete and destroy entirely data.
    await pgDataSource.dropDatabase();
    await pgDataSource.destroy();
  });

  it("should be able to authenticate user session", async () => {
    // Authenticate user session.
    const response = await request(app)
      .post("/api/v1/session/authenticate")
      .send({
        email: authUser.email,
        password: authUser.password,
      });

    // Get the refresh token saved at database for expecting test analisys.
    const userToken = await pgDataSource
      .createQueryBuilder<UserTokens>(UserTokens, "users_tokens")
      .where("users_tokens.user_id = :id", { id: authUser.id })
      .getOne();

    expect(response.status).toBe(200);
    expect(userToken).toBeInstanceOf(UserTokens);
    expect(response.body).toHaveProperty("token");
    expect(response.body.user.id).toBe(authUser.id);
    expect(String(response.header["set-cookie"]).split("; ")[0]).toContain(
      userToken?.refresh_token
    );
  });

  it("should not be able to authenticate with an invalid email", async () => {
    const response = await request(app)
      .post("/api/v1/session/authenticate")
      .send({
        email: "invalid@email.com",
        password: authUser.password,
      });

    expect(response.status).toBe(401);
  });

  it("should not be able to authenticate with an invalid password", async () => {
    const response = await request(app)
      .post("/api/v1/session/authenticate")
      .send({
        email: authUser.email,
        password: "invalid-pass",
      });

    expect(response.status).toBe(401);
  });
});

let refreshToken: string;

describe("Refresh Session Controller", () => {
  beforeAll(async () => {
    // Connects at database and run migrations. It must be done in each test
    // controller file.
    await pgDataSource.initialize();
    await pgDataSource.runMigrations();

    // Create a user at "/api/v1/user" route to let possible to test sessions
    // controllers.
    const { body } = await request(app).post("/api/v1/user").send({
      name: "Name Sample",
      email: "sample@email.com",
      password: "samplepass",
    });

    // Put that new user information inside a var.
    authUser = {
      ...body,
      password: "samplepass",
    };
  });

  afterAll(async () => {
    // Delete and destroy entirely data.
    await pgDataSource.dropDatabase();
    await pgDataSource.destroy();
  });

  beforeEach(async () => {
    // Authenticate user session at "/api/v1/session/authenticate" route to
    // create a cookie of a refresh token.
    const response = await request(app)
      .post("/api/v1/session/authenticate")
      .send({
        email: authUser.email,
        password: authUser.password,
      });

    // Getting cookied token generated by last authentication.
    [refreshToken] = String(response.headers["set-cookie"]).split("; ");
    [, refreshToken] = String(refreshToken).split("refresh_token=");

    // This helps 'jsonwebtoken' to generate a different token. Otherwise, the
    // same token will be generated
    await delay(1000);
  });

  afterEach(async () => {
    // This helps 'jsonwebtoken' to generate a different token. Otherwise, the
    // same token will be generated
    await delay(1000);
  });

  it("should be able to refresh user session token", async () => {
    // Refresh user session token.
    const response = await request(app)
      .post("/api/v1/session/refresh-token")
      .set("Accept-Language", "en")
      .set("Cookie", [`refresh_token=${refreshToken}`]);

    // Manipulating returned cookie to get the new generated refresh token.
    [refreshToken] = String(response.headers["set-cookie"]).split("; ");
    [, refreshToken] = String(refreshToken).split("refresh_token=");

    // Get the refresh token saved at database for expecting test analisys.
    const userToken = await pgDataSource
      .createQueryBuilder<UserTokens>(UserTokens, "users_tokens")
      .where("users_tokens.refresh_token = :refreshToken", { refreshToken })
      .getOne();

    expect(response.status).toBe(200);
    expect(userToken).toBeInstanceOf(UserTokens);
    expect(response.body).toHaveProperty("token");
    // expect(response.body.user.id).toBe(authUser.id);
    expect(String(response.header["set-cookie"]).split("; ")[0]).toContain(
      userToken?.refresh_token
    );
  });

  it("should not be able to refresh with an invalid token", async () => {
    const response = await request(app)
      .post("/api/v1/session/refresh-token")
      .set("Accept-Language", "en")
      .set("Cookie", ["invalid-refresh-token"]);

    expect(response.status).toBe(401);
  });

  it("should not be able to refresh with an unfound token", async () => {
    // Deleting valid token of database
    await pgDataSource
      .createQueryBuilder()
      .delete()
      .from(UserTokens)
      .where("refresh_token = :refreshToken", { refreshToken })
      .execute();

    const response = await request(app)
      .post("/api/v1/session/refresh-token")
      .set("Accept-Language", "en")
      .set("Cookie", [`refresh_token=${refreshToken}`]);

    expect(response.status).toBe(401);
  });

  it("should not be able to refresh with an expired token", async () => {
    jest.spyOn(utilDate, "dateNow").mockImplementationOnce(() => {
      return new Date("2199-12-17T00:00:00");
    });

    const response = await request(app)
      .post("/api/v1/session/refresh-token")
      .set("Accept-Language", "en")
      .set("Cookie", [`refresh_token=${refreshToken}`]);

    expect(response.status).toBe(401);
  });

  it("should not be able to refresh with a revoked token", async () => {
    await request(app)
      .post("/api/v1/session/refresh-token")
      .set("Accept-Language", "en")
      .set("Cookie", [`refresh_token=${refreshToken}`]);

    const response = await request(app)
      .post("/api/v1/session/refresh-token")
      .set("Accept-Language", "en")
      .set("Cookie", [`refresh_token=${refreshToken}`]);

    expect(response.status).toBe(401);
  });
});

describe("Revoke Session Controller", () => {
  beforeAll(async () => {
    // Connects at database and run migrations. It must be done in each test
    // controller file.
    await pgDataSource.initialize();
    await pgDataSource.runMigrations();

    // Create a user at "/api/v1/user" route to let possible to test sessions
    // controllers.
    const { body } = await request(app).post("/api/v1/user").send({
      name: "Name Sample",
      email: "sample@email.com",
      password: "samplepass",
    });

    // Put that new user information inside a var.
    authUser = {
      ...body,
      password: "samplepass",
    };
  });

  afterAll(async () => {
    // Delete and destroy entirely data.
    await pgDataSource.dropDatabase();
    await pgDataSource.destroy();
  });

  beforeEach(async () => {
    // Authenticate user session at "/api/v1/session/authenticate" route to
    // create a cookie of a refresh token.
    const response = await request(app)
      .post("/api/v1/session/authenticate")
      .send({
        email: authUser.email,
        password: authUser.password,
      });

    // Getting cookied token generated by last authentication.
    [refreshToken] = String(response.headers["set-cookie"]).split("; ");
    [, refreshToken] = String(refreshToken).split("refresh_token=");

    // This helps 'jsonwebtoken' to generate a different token. Otherwise, the
    // same token will be generated
    await delay(1000);
  });

  afterEach(async () => {
    // This helps 'jsonwebtoken' to generate a different token. Otherwise, the
    // same token will be generated
    await delay(1000);
  });

  it("should be able to revoke user session token", async () => {
    // revoke user session token.
    const response = await request(app)
      .post("/api/v1/session/revoke-token")
      .set("Accept-Language", "en")
      .set("Cookie", [`refresh_token=${refreshToken}`]);

    // Get the revoked token saved at database for expecting test analisys.
    const userToken =
      (await pgDataSource
        .createQueryBuilder<UserTokens>(UserTokens, "users_tokens")
        .where("users_tokens.refresh_token = :refreshToken", { refreshToken })
        .getOne()) || new UserTokens();

    expect(response.status).toBe(200);
    expect(userToken).toBeInstanceOf(UserTokens);
    expect(userToken.revoked_reason).toBe("Refresh token revoked by user.");
  });

  it("should not be able to revoke with an invalid token", async () => {
    const response = await request(app)
      .post("/api/v1/session/revoke-token")
      .set("Accept-Language", "en")
      .set("Cookie", ["invalid-refresh-token"]);

    expect(response.status).toBe(401);
  });

  it("should not be able to revoke with an unfound token", async () => {
    // Deleting valid token of database
    await pgDataSource
      .createQueryBuilder()
      .delete()
      .from(UserTokens)
      .where("refresh_token = :refreshToken", { refreshToken })
      .execute();

    const response = await request(app)
      .post("/api/v1/session/revoke-token")
      .set("Accept-Language", "en")
      .set("Cookie", [`refresh_token=${refreshToken}`]);

    expect(response.status).toBe(401);
  });

  it("should not be able to revoke with an expired token", async () => {
    jest.spyOn(utilDate, "dateNow").mockImplementationOnce(() => {
      return new Date("2199-12-17T00:00:00");
    });

    const response = await request(app)
      .post("/api/v1/session/revoke-token")
      .set("Accept-Language", "en")
      .set("Cookie", [`refresh_token=${refreshToken}`]);

    expect(response.status).toBe(401);
  });

  it("should not be able to revoke with a revoked token", async () => {
    await request(app)
      .post("/api/v1/session/revoke-token")
      .set("Accept-Language", "en")
      .set("Cookie", [`refresh_token=${refreshToken}`]);

    const response = await request(app)
      .post("/api/v1/session/revoke-token")
      .set("Accept-Language", "en")
      .set("Cookie", [`refresh_token=${refreshToken}`]);

    expect(response.status).toBe(401);
  });
});
